name: en_logger
description: EnLogger allows you to write log messages according to your needs without restricting you to writing messages to the debug console or other systems.
version: 1.1.1
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/en_logger
topics: [ log, severity, logger, debug ]

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
